<?php if(!$this->session->get(IS_LOGGED_IN)): ?>
    <p>Login to view videos and modify your uploaded videos.</p>
<?php else: ?>
    <style type="text/css">
        .list-group{
            max-height: 800px;
            margin-bottom: 10px;
            overflow:scroll;
            -webkit-overflow-scrolling: touch;
        }
    </style>

    <p></p>

    <div class="row">
        <div class="col-lg-9">
            <div class="embed-responsive embed-responsive-16by9">
                <video class="embed-responsive-item"
                       <?php echo 'src="' . FQDN . '/videos/index/0" controls>'; ?>
                    Browser does not support HTML5 video playback.
                </video>
            </div>
            <p></p>
        </div>

        <div class="col-lg-3">
            <button type="button" class="mb-4 btn btn-primary btn-block"
                    onclick="window.location = '/videos/upload'">Upload</button>

            <ul class="list-group">
                <li class="list-group-item">
                    <?php
                        //TODO: Implement volt templates.
                        if(isset($videosList))
                        {
                            echo $videosList;
                        }
                        else
                        {
                            echo "No videos uploaded.";
                        }
                    ?>
                </li>
            </ul>
        </div>
    </div>
<?php endif; ?>