<?php
?>

<div class="row">
    <div class="col-lg-6">
        <p>Choose video file to upload:</p>
        <form action="/videos/save" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <input type="file" id="videoFile" name="videoFile">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

