<?php
    if($this->session->get(IS_LOGGED_IN))
    {
        header('Location: /');
        exit();
    }
?>

<h2 class="text-center">Login using this form</h2>

<?php
echo $this->tag->form(
    [
        "login/index",
        "method" => "post",
        "class" => ""
    ]
);
?>

<div class="form-group">
    <label for="name">Name</label>
    <?php echo $this->tag->textField(
        [
            "name",
            "class" => "form-control",
            "placeholder" => "Enter Your Username"
        ]); ?>
</div>

<div class="form-group">
    <label for="email">Email</label>
    <?php echo $this->tag->emailField(
        [
            "email",
            "class" => "form-control",
            "placeholder" => "Enter Your Email"
        ]); ?>
</div>

<p>
    <?php echo $this->tag->submitButton(
        [
            "Login",
            "class" => "btn btn-primary"
        ]
    ); ?>
</p>

<?php echo $this->tag->endForm(); ?>

<?php
if(isset($invalid) && $invalid === true)
{
    echo "<p class='text-danger'>$message</p>";
}
elseif($this->session->get(IS_LOGGED_IN))
{
    header('Location: /');
    exit();
}
?>
